### ISSUE TITLE
Cannot open Combat Tracker config on v12

### ISSUE THREAD

**Issue by BoltsJ** [foundryvtt/worldbuilding#65]
Attempting to open the Combat tracker configuration on v12 throws an error and fails to open the window.

To reproduce:
1. Launch a world on v12
2. Click the cog icon in the combat tracker
3. The config window doesn't open and the following error is printed to the console:
![image](https://github.com/user-attachments/assets/1728fd96-772c-4f8a-8898-3226f4220213)

This happens even with no modules enabled.

**Comment by zorida** [comment]
Same for me on Simple Worldbuilding with Foundry v.12 build 328, no dialog opens and I receive this kind of error. Note that the same error arises even without the lib-wrapper module or with no module installed. Cannot read properties of undefined (reading 'Actor'). Same kind of error when I try to open Configure Default Token Settings

```
Error: An error occurred while rendering CombatTrackerConfig 27. Cannot read properties of undefined (reading 'Actor')
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5770:13
onError @ foundry.js:631
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5770
Promise.catch (async)
render @ foundry.js:5768
onClickSubmenuWrapper @ colorSetting.js:21
🎁call_wrapper @ libWrapper-wrapper.js:591
🎁SettingsConfig.prototype._onClickSubmenu#0 @ libWrapper-wrapper.js:189
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2```

**Comment by MagrothJ** [comment]
The same happens for me. No modules activated.
![image](https://github.com/user-attachments/assets/a62ca2c5-c0e2-44ef-a487-b3ab4bf62bee)
